### ISSUE TITLE
Question about the preprocess of the LA dataset.

### ISSUE THREAD

**Issue by xqcn** [yulequan/UA-MT#6]
@yulequan 
I have noticed that in the preprocessing of the LA dataset, a patch with the size [112,112,80] is cropped according to the label center, and 20-40 is entended along the x, y axis, 10-20 is extended along the z axis.
There is a  question that in my opinion, the position of the left atrial should not be known if the sample is used as the unlabeled data in the preprocessing. I wonder if you have considered using the whole scans as unlabeled data.
I can not download the LA dataset, but I have tried your method on other dataset, it seems that UA-MT just works when I use the label centered occasion, or the performance is worse than the vnet_dp using the whole scans (also random crop).
By the way, could you tell me the original spacing and scan size of the LA dataset, and is it changed in your experiments?

**Comment by yulequan** [comment]
@xqcn , Thanks for your interest in our work. Yes, we crop the LA from the dataset.  In this method, we mainly focus on evaluating the effectiveness of semi-supervised learning, not only improve the absolute performance of LA segmentation. Therefore, we first crop the foreground. In the real test cases, we can first train a localization network to detect the rough position first. 

For the experiments on the whole scan, I think the performance degradation may be caused by the imbalance of foreground and background samples. 

If I am correct, we do not change the original spacing of dataset and we did not employ scaling operation to preprocess the dataset.

**Comment by xqcn** [comment]
@yulequan 
I see. Thank you very much!
